[package]
description = "wayland-parser"
edition     = { workspace = true }
license     = { workspace = true }
name        = "wayland-parser"
version     = { workspace = true }


[lints]
workspace = true


[dependencies]
kerror = { workspace = true }
