[package]
description = "kerror"
edition     = { workspace = true }
license     = { workspace = true }
name        = "kerror"
version     = { workspace = true }


[lints]
workspace = true


[dependencies]
thiserror = { workspace = true }

rkyv = { workspace = true }
toml = { workspace = true }
