name: CI Action

on: [workflow_dispatch, push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-insta

      - name: Run test
        run: cargo xtest --verbose --release

      - name: Build
        run: cargo build --verbose

      - name: Run xtask
        run: cargo xtask --verbose
